version: 2.1

jobs:
  build:
    docker:
      - image: barichello/godot-ci
    steps:
      - checkout
      - run: |
          mkdir -p ./build/html
          mkdir -p ./build/windows
          mkdir -p ./build/macos
          mkdir -p ./build/linux
      - run: godot --export HTML5 ./build/html/index.html
      - run:
          name: Cloudflare deploy
          command: bash .circleci/deploy-cloudflare.sh
      - run: godot --export "Windows Desktop" ./build/windows/SpaceExplorer.exe
      - run: godot --export "Linux/X11" ./build/linux/SpaceExplorer
      - run: godot --export "Mac OSX" ./build/macos/SpaceExplorer.app
      - run:
          name: Github release
          command: bash .circleci/release.sh

workflows:
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
